sudo: required
dist: trusty
language: scala
scala:
  - 2.12.4
  - 2.11.11
before_install:
  - wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1MamroXce-EwbR-KFMpxBvRhWWk4x_mXs' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1MamroXce-EwbR-KFMpxBvRhWWk4x_mXs" -O libdynet.so && rm -rf /tmp/cookies.txt

