/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class AdamTrainer extends Trainer {
  private transient long swigCPtr;

  protected AdamTrainer(long cPtr, boolean cMemoryOwn) {
    super(dynet_swigJNI.AdamTrainer_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AdamTrainer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_AdamTrainer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AdamTrainer(ParameterCollection m, float learning_rate, float beta_1, float beta_2, float eps) {
    this(dynet_swigJNI.new_AdamTrainer__SWIG_0(ParameterCollection.getCPtr(m), m, learning_rate, beta_1, beta_2, eps), true);
  }

  public AdamTrainer(ParameterCollection m, float learning_rate, float beta_1, float beta_2) {
    this(dynet_swigJNI.new_AdamTrainer__SWIG_1(ParameterCollection.getCPtr(m), m, learning_rate, beta_1, beta_2), true);
  }

  public AdamTrainer(ParameterCollection m, float learning_rate, float beta_1) {
    this(dynet_swigJNI.new_AdamTrainer__SWIG_2(ParameterCollection.getCPtr(m), m, learning_rate, beta_1), true);
  }

  public AdamTrainer(ParameterCollection m, float learning_rate) {
    this(dynet_swigJNI.new_AdamTrainer__SWIG_3(ParameterCollection.getCPtr(m), m, learning_rate), true);
  }

  public AdamTrainer(ParameterCollection m) {
    this(dynet_swigJNI.new_AdamTrainer__SWIG_4(ParameterCollection.getCPtr(m), m), true);
  }

  public void restart() {
    dynet_swigJNI.AdamTrainer_restart(swigCPtr, this);
  }

}
