/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class Callback {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Callback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Callback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_Callback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    dynet_swigJNI.Callback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    dynet_swigJNI.Callback_change_ownership(this, swigCPtr, true);
  }

  public Callback() {
    this(dynet_swigJNI.new_Callback(), true);
    dynet_swigJNI.Callback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void run() {
    if (getClass() == Callback.class) dynet_swigJNI.Callback_run(swigCPtr, this); else dynet_swigJNI.Callback_runSwigExplicitCallback(swigCPtr, this);
  }

}
