/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class DynetParams {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DynetParams(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DynetParams obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_DynetParams(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRandom_seed(long value) {
    dynet_swigJNI.DynetParams_random_seed_set(swigCPtr, this, value);
  }

  public long getRandom_seed() {
    return dynet_swigJNI.DynetParams_random_seed_get(swigCPtr, this);
  }

  public void setMem_descriptor(String value) {
    dynet_swigJNI.DynetParams_mem_descriptor_set(swigCPtr, this, value);
  }

  public String getMem_descriptor() {
    return dynet_swigJNI.DynetParams_mem_descriptor_get(swigCPtr, this);
  }

  public void setWeight_decay(float value) {
    dynet_swigJNI.DynetParams_weight_decay_set(swigCPtr, this, value);
  }

  public float getWeight_decay() {
    return dynet_swigJNI.DynetParams_weight_decay_get(swigCPtr, this);
  }

  public void setAutobatch(int value) {
    dynet_swigJNI.DynetParams_autobatch_set(swigCPtr, this, value);
  }

  public int getAutobatch() {
    return dynet_swigJNI.DynetParams_autobatch_get(swigCPtr, this);
  }

  public void setProfiling(int value) {
    dynet_swigJNI.DynetParams_profiling_set(swigCPtr, this, value);
  }

  public int getProfiling() {
    return dynet_swigJNI.DynetParams_profiling_get(swigCPtr, this);
  }

  public void setForward_only(int value) {
    dynet_swigJNI.DynetParams_forward_only_set(swigCPtr, this, value);
  }

  public int getForward_only() {
    return dynet_swigJNI.DynetParams_forward_only_get(swigCPtr, this);
  }

  public void setShared_parameters(boolean value) {
    dynet_swigJNI.DynetParams_shared_parameters_set(swigCPtr, this, value);
  }

  public boolean getShared_parameters() {
    return dynet_swigJNI.DynetParams_shared_parameters_get(swigCPtr, this);
  }

  public void setDynamic(boolean value) {
    dynet_swigJNI.DynetParams_dynamic_set(swigCPtr, this, value);
  }

  public boolean getDynamic() {
    return dynet_swigJNI.DynetParams_dynamic_get(swigCPtr, this);
  }

  public DynetParams() {
    this(dynet_swigJNI.new_DynetParams(), true);
  }

}
