/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class Expression {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Expression(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Expression obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_Expression(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPg(ComputationGraph value) {
    dynet_swigJNI.Expression_pg_set(swigCPtr, this, ComputationGraph.getCPtr(value), value);
  }

  public ComputationGraph getPg() {
    long cPtr = dynet_swigJNI.Expression_pg_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ComputationGraph(cPtr, false);
  }

  public void setI(SWIGTYPE_p_dynet__VariableIndex value) {
    dynet_swigJNI.Expression_i_set(swigCPtr, this, SWIGTYPE_p_dynet__VariableIndex.getCPtr(value));
  }

  public SWIGTYPE_p_dynet__VariableIndex getI() {
    long cPtr = dynet_swigJNI.Expression_i_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_dynet__VariableIndex(cPtr, false);
  }

  public Expression(ComputationGraph pg, SWIGTYPE_p_dynet__VariableIndex i) {
    this(dynet_swigJNI.new_Expression(ComputationGraph.getCPtr(pg), pg, SWIGTYPE_p_dynet__VariableIndex.getCPtr(i)), true);
  }

  public Tensor value() {
    return new Tensor(dynet_swigJNI.Expression_value(swigCPtr, this), false);
  }

  public Dim dim() {
    return new Dim(dynet_swigJNI.Expression_dim(swigCPtr, this), false);
  }

}
