/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class ExpressionVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ExpressionVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExpressionVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_ExpressionVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ExpressionVector(java.util.Collection<Expression> values) {
     this(values.size());
     int i = 0;
     for (java.util.Iterator<Expression> it = values.iterator(); it.hasNext(); i++) {
         Expression value = it.next();
         this.set(i, value);
     }
  }

  public ExpressionVector() {
    this(dynet_swigJNI.new_ExpressionVector__SWIG_0(), true);
  }

  public ExpressionVector(long n) {
    this(dynet_swigJNI.new_ExpressionVector__SWIG_1(n), true);
  }

  public long size() {
    return dynet_swigJNI.ExpressionVector_size(swigCPtr, this);
  }

  public long capacity() {
    return dynet_swigJNI.ExpressionVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    dynet_swigJNI.ExpressionVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return dynet_swigJNI.ExpressionVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    dynet_swigJNI.ExpressionVector_clear(swigCPtr, this);
  }

  public void add(Expression x) {
    dynet_swigJNI.ExpressionVector_add(swigCPtr, this, Expression.getCPtr(x), x);
  }

  public Expression get(int i) {
    return new Expression(dynet_swigJNI.ExpressionVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, Expression val) {
    dynet_swigJNI.ExpressionVector_set(swigCPtr, this, i, Expression.getCPtr(val), val);
  }

}
