/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class GRUBuilder extends RNNBuilder {
  private transient long swigCPtr;

  protected GRUBuilder(long cPtr, boolean cMemoryOwn) {
    super(dynet_swigJNI.GRUBuilder_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GRUBuilder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_GRUBuilder(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public GRUBuilder() {
    this(dynet_swigJNI.new_GRUBuilder__SWIG_0(), true);
  }

  public GRUBuilder(long layers, long input_dim, long hidden_dim, ParameterCollection model) {
    this(dynet_swigJNI.new_GRUBuilder__SWIG_1(layers, input_dim, hidden_dim, ParameterCollection.getCPtr(model), model), true);
  }

  public Expression back() {
    return new Expression(dynet_swigJNI.GRUBuilder_back(swigCPtr, this), true);
  }

  public ExpressionVector final_h() {
    return new ExpressionVector(dynet_swigJNI.GRUBuilder_final_h(swigCPtr, this), true);
  }

  public ExpressionVector final_s() {
    return new ExpressionVector(dynet_swigJNI.GRUBuilder_final_s(swigCPtr, this), true);
  }

  public ExpressionVector get_h(int i) {
    return new ExpressionVector(dynet_swigJNI.GRUBuilder_get_h(swigCPtr, this, i), true);
  }

  public ExpressionVector get_s(int i) {
    return new ExpressionVector(dynet_swigJNI.GRUBuilder_get_s(swigCPtr, this, i), true);
  }

  public long num_h0_components() {
    return dynet_swigJNI.GRUBuilder_num_h0_components(swigCPtr, this);
  }

  public void copy(RNNBuilder params) {
    dynet_swigJNI.GRUBuilder_copy(swigCPtr, this, RNNBuilder.getCPtr(params), params);
  }

  public ParameterCollection get_parameter_collection() {
    return new ParameterCollection(dynet_swigJNI.GRUBuilder_get_parameter_collection(swigCPtr, this), false);
  }

  public GRUBuilder(GRUBuilder other) {
    this(dynet_swigJNI.new_GRUBuilder__SWIG_2(GRUBuilder.getCPtr(other), other), true);
  }

}
