/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class Loader {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Loader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Loader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_Loader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void populate(ParameterCollection model, String key) {
    dynet_swigJNI.Loader_populate__SWIG_0(swigCPtr, this, ParameterCollection.getCPtr(model), model, key);
  }

  public void populate(ParameterCollection model) {
    dynet_swigJNI.Loader_populate__SWIG_1(swigCPtr, this, ParameterCollection.getCPtr(model), model);
  }

  public void populate(Parameter param, String key) {
    dynet_swigJNI.Loader_populate__SWIG_2(swigCPtr, this, Parameter.getCPtr(param), param, key);
  }

  public void populate(Parameter param) {
    dynet_swigJNI.Loader_populate__SWIG_3(swigCPtr, this, Parameter.getCPtr(param), param);
  }

  public void populate(LookupParameter lookup_param, String key) {
    dynet_swigJNI.Loader_populate__SWIG_4(swigCPtr, this, LookupParameter.getCPtr(lookup_param), lookup_param, key);
  }

  public void populate(LookupParameter lookup_param) {
    dynet_swigJNI.Loader_populate__SWIG_5(swigCPtr, this, LookupParameter.getCPtr(lookup_param), lookup_param);
  }

  public Parameter load_param(ParameterCollection model, String key) {
    return new Parameter(dynet_swigJNI.Loader_load_param(swigCPtr, this, ParameterCollection.getCPtr(model), model, key), true);
  }

  public LookupParameter load_lookup_param(ParameterCollection model, String key) {
    return new LookupParameter(dynet_swigJNI.Loader_load_lookup_param(swigCPtr, this, ParameterCollection.getCPtr(model), model, key), true);
  }

}
