/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class LookupParameterStorageVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LookupParameterStorageVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LookupParameterStorageVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_LookupParameterStorageVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LookupParameterStorageVector() {
    this(dynet_swigJNI.new_LookupParameterStorageVector__SWIG_0(), true);
  }

  public LookupParameterStorageVector(long n) {
    this(dynet_swigJNI.new_LookupParameterStorageVector__SWIG_1(n), true);
  }

  public long size() {
    return dynet_swigJNI.LookupParameterStorageVector_size(swigCPtr, this);
  }

  public long capacity() {
    return dynet_swigJNI.LookupParameterStorageVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    dynet_swigJNI.LookupParameterStorageVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return dynet_swigJNI.LookupParameterStorageVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    dynet_swigJNI.LookupParameterStorageVector_clear(swigCPtr, this);
  }

  public void add(LookupParameterStorage x) {
    dynet_swigJNI.LookupParameterStorageVector_add(swigCPtr, this, LookupParameterStorage.getCPtr(x), x);
  }

  public LookupParameterStorage get(int i) {
    long cPtr = dynet_swigJNI.LookupParameterStorageVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new LookupParameterStorage(cPtr, true);
  }

  public void set(int i, LookupParameterStorage val) {
    dynet_swigJNI.LookupParameterStorageVector_set(swigCPtr, this, i, LookupParameterStorage.getCPtr(val), val);
  }

}
