/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class NaryTreeLSTMBuilder extends TreeLSTMBuilder {
  private transient long swigCPtr;

  protected NaryTreeLSTMBuilder(long cPtr, boolean cMemoryOwn) {
    super(dynet_swigJNI.NaryTreeLSTMBuilder_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NaryTreeLSTMBuilder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_NaryTreeLSTMBuilder(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public NaryTreeLSTMBuilder(long N, long layers, long input_dim, long hidden_dim, ParameterCollection model) {
    this(dynet_swigJNI.new_NaryTreeLSTMBuilder__SWIG_0(N, layers, input_dim, hidden_dim, ParameterCollection.getCPtr(model), model), true);
  }

  public void set_num_elements(int num) {
    dynet_swigJNI.NaryTreeLSTMBuilder_set_num_elements(swigCPtr, this, num);
  }

  public Expression add_input(int id, IntVector children, Expression x) {
    return new Expression(dynet_swigJNI.NaryTreeLSTMBuilder_add_input(swigCPtr, this, id, IntVector.getCPtr(children), children, Expression.getCPtr(x), x), true);
  }

  public void copy(RNNBuilder params) {
    dynet_swigJNI.NaryTreeLSTMBuilder_copy(swigCPtr, this, RNNBuilder.getCPtr(params), params);
  }

  public ParameterCollection get_parameter_collection() {
    return new ParameterCollection(dynet_swigJNI.NaryTreeLSTMBuilder_get_parameter_collection(swigCPtr, this), false);
  }

  public void setHas_initial_state(boolean value) {
    dynet_swigJNI.NaryTreeLSTMBuilder_has_initial_state_set(swigCPtr, this, value);
  }

  public boolean getHas_initial_state() {
    return dynet_swigJNI.NaryTreeLSTMBuilder_has_initial_state_get(swigCPtr, this);
  }

  public void setH0(ExpressionVector value) {
    dynet_swigJNI.NaryTreeLSTMBuilder_h0_set(swigCPtr, this, ExpressionVector.getCPtr(value), value);
  }

  public ExpressionVector getH0() {
    long cPtr = dynet_swigJNI.NaryTreeLSTMBuilder_h0_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ExpressionVector(cPtr, false);
  }

  public void setC0(ExpressionVector value) {
    dynet_swigJNI.NaryTreeLSTMBuilder_c0_set(swigCPtr, this, ExpressionVector.getCPtr(value), value);
  }

  public ExpressionVector getC0() {
    long cPtr = dynet_swigJNI.NaryTreeLSTMBuilder_c0_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ExpressionVector(cPtr, false);
  }

  public void setLayers(long value) {
    dynet_swigJNI.NaryTreeLSTMBuilder_layers_set(swigCPtr, this, value);
  }

  public long getLayers() {
    return dynet_swigJNI.NaryTreeLSTMBuilder_layers_get(swigCPtr, this);
  }

  public void setN(long value) {
    dynet_swigJNI.NaryTreeLSTMBuilder_N_set(swigCPtr, this, value);
  }

  public long getN() {
    return dynet_swigJNI.NaryTreeLSTMBuilder_N_get(swigCPtr, this);
  }

  public NaryTreeLSTMBuilder(NaryTreeLSTMBuilder other) {
    this(dynet_swigJNI.new_NaryTreeLSTMBuilder__SWIG_1(NaryTreeLSTMBuilder.getCPtr(other), other), true);
  }

}
