/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class ParameterInitNormal extends ParameterInit {
  private transient long swigCPtr;

  protected ParameterInitNormal(long cPtr, boolean cMemoryOwn) {
    super(dynet_swigJNI.ParameterInitNormal_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParameterInitNormal obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_ParameterInitNormal(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ParameterInitNormal(float m, float v) {
    this(dynet_swigJNI.new_ParameterInitNormal__SWIG_0(m, v), true);
  }

  public ParameterInitNormal(float m) {
    this(dynet_swigJNI.new_ParameterInitNormal__SWIG_1(m), true);
  }

  public ParameterInitNormal() {
    this(dynet_swigJNI.new_ParameterInitNormal__SWIG_2(), true);
  }

  public void initialize_params(Tensor values) {
    dynet_swigJNI.ParameterInitNormal_initialize_params(swigCPtr, this, Tensor.getCPtr(values), values);
  }

}
