/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class ParameterVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParameterVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParameterVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_ParameterVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ParameterVector(java.util.Collection<Parameter> values) {
     this(values.size());
     int i = 0;
     for (java.util.Iterator<Parameter> it = values.iterator(); it.hasNext(); i++) {
         Parameter value = it.next();
         this.set(i, value);
     }
  }

  public ParameterVector() {
    this(dynet_swigJNI.new_ParameterVector__SWIG_0(), true);
  }

  public ParameterVector(long n) {
    this(dynet_swigJNI.new_ParameterVector__SWIG_1(n), true);
  }

  public long size() {
    return dynet_swigJNI.ParameterVector_size(swigCPtr, this);
  }

  public long capacity() {
    return dynet_swigJNI.ParameterVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    dynet_swigJNI.ParameterVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return dynet_swigJNI.ParameterVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    dynet_swigJNI.ParameterVector_clear(swigCPtr, this);
  }

  public void add(Parameter x) {
    dynet_swigJNI.ParameterVector_add(swigCPtr, this, Parameter.getCPtr(x), x);
  }

  public Parameter get(int i) {
    return new Parameter(dynet_swigJNI.ParameterVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, Parameter val) {
    dynet_swigJNI.ParameterVector_set(swigCPtr, this, i, Parameter.getCPtr(val), val);
  }

}
