/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class ParameterStorageBase {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParameterStorageBase(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParameterStorageBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_ParameterStorageBase(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void scale_parameters(float a) {
    dynet_swigJNI.ParameterStorageBase_scale_parameters(swigCPtr, this, a);
  }

  public void zero() {
    dynet_swigJNI.ParameterStorageBase_zero(swigCPtr, this);
  }

  public void squared_l2norm(SWIGTYPE_p_float sqnorm) {
    dynet_swigJNI.ParameterStorageBase_squared_l2norm(swigCPtr, this, SWIGTYPE_p_float.getCPtr(sqnorm));
  }

  public void g_squared_l2norm(SWIGTYPE_p_float sqnorm) {
    dynet_swigJNI.ParameterStorageBase_g_squared_l2norm(swigCPtr, this, SWIGTYPE_p_float.getCPtr(sqnorm));
  }

  public long size() {
    return dynet_swigJNI.ParameterStorageBase_size(swigCPtr, this);
  }

}
