/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class ParameterCollection {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParameterCollection(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParameterCollection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_ParameterCollection(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ParameterCollection() {
    this(dynet_swigJNI.new_ParameterCollection(), true);
  }

  public float gradient_l2_norm() {
    return dynet_swigJNI.ParameterCollection_gradient_l2_norm(swigCPtr, this);
  }

  public void reset_gradient() {
    dynet_swigJNI.ParameterCollection_reset_gradient(swigCPtr, this);
  }

  public Parameter add_parameters(Dim d, float scale) {
    return new Parameter(dynet_swigJNI.ParameterCollection_add_parameters__SWIG_0(swigCPtr, this, Dim.getCPtr(d), d, scale), true);
  }

  public Parameter add_parameters(Dim d) {
    return new Parameter(dynet_swigJNI.ParameterCollection_add_parameters__SWIG_1(swigCPtr, this, Dim.getCPtr(d), d), true);
  }

  public Parameter add_parameters(Dim d, ParameterInit init) {
    return new Parameter(dynet_swigJNI.ParameterCollection_add_parameters__SWIG_2(swigCPtr, this, Dim.getCPtr(d), d, ParameterInit.getCPtr(init), init), true);
  }

  public LookupParameter add_lookup_parameters(long n, Dim d) {
    return new LookupParameter(dynet_swigJNI.ParameterCollection_add_lookup_parameters__SWIG_0(swigCPtr, this, n, Dim.getCPtr(d), d), true);
  }

  public LookupParameter add_lookup_parameters(long n, Dim d, ParameterInit init) {
    return new LookupParameter(dynet_swigJNI.ParameterCollection_add_lookup_parameters__SWIG_1(swigCPtr, this, n, Dim.getCPtr(d), d, ParameterInit.getCPtr(init), init), true);
  }

  public void project_weights(float radius) {
    dynet_swigJNI.ParameterCollection_project_weights__SWIG_0(swigCPtr, this, radius);
  }

  public void project_weights() {
    dynet_swigJNI.ParameterCollection_project_weights__SWIG_1(swigCPtr, this);
  }

  public void set_weight_decay_lambda(float lambda) {
    dynet_swigJNI.ParameterCollection_set_weight_decay_lambda(swigCPtr, this, lambda);
  }

  public long parameter_count() {
    return dynet_swigJNI.ParameterCollection_parameter_count(swigCPtr, this);
  }

  public long updated_parameter_count() {
    return dynet_swigJNI.ParameterCollection_updated_parameter_count(swigCPtr, this);
  }

  public ParameterStorageVector parameters_list() {
    return new ParameterStorageVector(dynet_swigJNI.ParameterCollection_parameters_list(swigCPtr, this), true);
  }

  public LookupParameterStorageVector lookup_parameters_list() {
    return new LookupParameterStorageVector(dynet_swigJNI.ParameterCollection_lookup_parameters_list(swigCPtr, this), true);
  }

}
