/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class ParameterVectorVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParameterVectorVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParameterVectorVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_ParameterVectorVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ParameterVectorVector(java.util.Collection<ParameterVector> values) {
     this(values.size());
     int i = 0;
     for (java.util.Iterator<ParameterVector> it = values.iterator(); it.hasNext(); i++) {
         ParameterVector value = it.next();
         this.set(i, value);
     }
  }

  public ParameterVectorVector() {
    this(dynet_swigJNI.new_ParameterVectorVector__SWIG_0(), true);
  }

  public ParameterVectorVector(long n) {
    this(dynet_swigJNI.new_ParameterVectorVector__SWIG_1(n), true);
  }

  public long size() {
    return dynet_swigJNI.ParameterVectorVector_size(swigCPtr, this);
  }

  public long capacity() {
    return dynet_swigJNI.ParameterVectorVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    dynet_swigJNI.ParameterVectorVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return dynet_swigJNI.ParameterVectorVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    dynet_swigJNI.ParameterVectorVector_clear(swigCPtr, this);
  }

  public void add(ParameterVector x) {
    dynet_swigJNI.ParameterVectorVector_add(swigCPtr, this, ParameterVector.getCPtr(x), x);
  }

  public ParameterVector get(int i) {
    return new ParameterVector(dynet_swigJNI.ParameterVectorVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, ParameterVector val) {
    dynet_swigJNI.ParameterVectorVector_set(swigCPtr, this, i, ParameterVector.getCPtr(val), val);
  }

}
