/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class ParameterInit {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParameterInit(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParameterInit obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_ParameterInit(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void initialize_params(Tensor values) {
    dynet_swigJNI.ParameterInit_initialize_params(swigCPtr, this, Tensor.getCPtr(values), values);
  }

}
