/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class Saver {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Saver(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Saver obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_Saver(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void save(ParameterCollection model, String key) {
    dynet_swigJNI.Saver_save__SWIG_0(swigCPtr, this, ParameterCollection.getCPtr(model), model, key);
  }

  public void save(ParameterCollection model) {
    dynet_swigJNI.Saver_save__SWIG_1(swigCPtr, this, ParameterCollection.getCPtr(model), model);
  }

  public void save(Parameter param, String key) {
    dynet_swigJNI.Saver_save__SWIG_2(swigCPtr, this, Parameter.getCPtr(param), param, key);
  }

  public void save(Parameter param) {
    dynet_swigJNI.Saver_save__SWIG_3(swigCPtr, this, Parameter.getCPtr(param), param);
  }

  public void save(LookupParameter param, String key) {
    dynet_swigJNI.Saver_save__SWIG_4(swigCPtr, this, LookupParameter.getCPtr(param), param, key);
  }

  public void save(LookupParameter param) {
    dynet_swigJNI.Saver_save__SWIG_5(swigCPtr, this, LookupParameter.getCPtr(param), param);
  }

}
