/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class SimpleSGDTrainer extends Trainer {
  private transient long swigCPtr;

  protected SimpleSGDTrainer(long cPtr, boolean cMemoryOwn) {
    super(dynet_swigJNI.SimpleSGDTrainer_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SimpleSGDTrainer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_SimpleSGDTrainer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SimpleSGDTrainer(ParameterCollection m, float learning_rate) {
    this(dynet_swigJNI.new_SimpleSGDTrainer__SWIG_0(ParameterCollection.getCPtr(m), m, learning_rate), true);
  }

  public SimpleSGDTrainer(ParameterCollection m) {
    this(dynet_swigJNI.new_SimpleSGDTrainer__SWIG_1(ParameterCollection.getCPtr(m), m), true);
  }

  public void restart() {
    dynet_swigJNI.SimpleSGDTrainer_restart(swigCPtr, this);
  }

}
