/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class SimpleRNNBuilder extends RNNBuilder {
  private transient long swigCPtr;

  protected SimpleRNNBuilder(long cPtr, boolean cMemoryOwn) {
    super(dynet_swigJNI.SimpleRNNBuilder_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SimpleRNNBuilder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_SimpleRNNBuilder(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SimpleRNNBuilder() {
    this(dynet_swigJNI.new_SimpleRNNBuilder__SWIG_0(), true);
  }

  public SimpleRNNBuilder(long layers, long input_dim, long hidden_dim, ParameterCollection model, boolean support_lags) {
    this(dynet_swigJNI.new_SimpleRNNBuilder__SWIG_1(layers, input_dim, hidden_dim, ParameterCollection.getCPtr(model), model, support_lags), true);
  }

  public SimpleRNNBuilder(long layers, long input_dim, long hidden_dim, ParameterCollection model) {
    this(dynet_swigJNI.new_SimpleRNNBuilder__SWIG_2(layers, input_dim, hidden_dim, ParameterCollection.getCPtr(model), model), true);
  }

  public Expression add_auxiliary_input(Expression x, Expression aux) {
    return new Expression(dynet_swigJNI.SimpleRNNBuilder_add_auxiliary_input(swigCPtr, this, Expression.getCPtr(x), x, Expression.getCPtr(aux), aux), true);
  }

  public Expression back() {
    return new Expression(dynet_swigJNI.SimpleRNNBuilder_back(swigCPtr, this), true);
  }

  public ExpressionVector final_h() {
    return new ExpressionVector(dynet_swigJNI.SimpleRNNBuilder_final_h(swigCPtr, this), true);
  }

  public ExpressionVector final_s() {
    return new ExpressionVector(dynet_swigJNI.SimpleRNNBuilder_final_s(swigCPtr, this), true);
  }

  public ExpressionVector get_h(int i) {
    return new ExpressionVector(dynet_swigJNI.SimpleRNNBuilder_get_h(swigCPtr, this, i), true);
  }

  public ExpressionVector get_s(int i) {
    return new ExpressionVector(dynet_swigJNI.SimpleRNNBuilder_get_s(swigCPtr, this, i), true);
  }

  public void copy(RNNBuilder params) {
    dynet_swigJNI.SimpleRNNBuilder_copy(swigCPtr, this, RNNBuilder.getCPtr(params), params);
  }

  public long num_h0_components() {
    return dynet_swigJNI.SimpleRNNBuilder_num_h0_components(swigCPtr, this);
  }

  public ParameterCollection get_parameter_collection() {
    return new ParameterCollection(dynet_swigJNI.SimpleRNNBuilder_get_parameter_collection(swigCPtr, this), false);
  }

  public SimpleRNNBuilder(SimpleRNNBuilder other) {
    this(dynet_swigJNI.new_SimpleRNNBuilder__SWIG_3(SimpleRNNBuilder.getCPtr(other), other), true);
  }

}
