/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class Tensor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Tensor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Tensor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_Tensor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setD(Dim value) {
    dynet_swigJNI.Tensor_d_set(swigCPtr, this, Dim.getCPtr(value), value);
  }

  public Dim getD() {
    long cPtr = dynet_swigJNI.Tensor_d_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Dim(cPtr, false);
  }

  public void setV(SWIGTYPE_p_float value) {
    dynet_swigJNI.Tensor_v_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getV() {
    long cPtr = dynet_swigJNI.Tensor_v_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public Tensor() {
    this(dynet_swigJNI.new_Tensor(), true);
  }

}
