/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class TensorTools {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TensorTools(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TensorTools obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_TensorTools(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static float access_element(Tensor v, Dim index) {
    return dynet_swigJNI.TensorTools_access_element(Tensor.getCPtr(v), v, Dim.getCPtr(index), index);
  }

  public TensorTools() {
    this(dynet_swigJNI.new_TensorTools(), true);
  }

}
