/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class Trainer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Trainer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Trainer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_Trainer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void update() {
    dynet_swigJNI.Trainer_update(swigCPtr, this);
  }

  public void update_epoch(float r) {
    dynet_swigJNI.Trainer_update_epoch__SWIG_0(swigCPtr, this, r);
  }

  public void update_epoch() {
    dynet_swigJNI.Trainer_update_epoch__SWIG_1(swigCPtr, this);
  }

  public void restart() {
    dynet_swigJNI.Trainer_restart__SWIG_0(swigCPtr, this);
  }

  public void restart(float lr) {
    dynet_swigJNI.Trainer_restart__SWIG_1(swigCPtr, this, lr);
  }

  public float clip_gradients() {
    return dynet_swigJNI.Trainer_clip_gradients(swigCPtr, this);
  }

  public void rescale_and_reset_weight_decay() {
    dynet_swigJNI.Trainer_rescale_and_reset_weight_decay(swigCPtr, this);
  }

  public void setLearning_rate(float value) {
    dynet_swigJNI.Trainer_learning_rate_set(swigCPtr, this, value);
  }

  public float getLearning_rate() {
    return dynet_swigJNI.Trainer_learning_rate_get(swigCPtr, this);
  }

  public void setClipping_enabled(boolean value) {
    dynet_swigJNI.Trainer_clipping_enabled_set(swigCPtr, this, value);
  }

  public boolean getClipping_enabled() {
    return dynet_swigJNI.Trainer_clipping_enabled_get(swigCPtr, this);
  }

  public void setClip_threshold(float value) {
    dynet_swigJNI.Trainer_clip_threshold_set(swigCPtr, this, value);
  }

  public float getClip_threshold() {
    return dynet_swigJNI.Trainer_clip_threshold_get(swigCPtr, this);
  }

  public void setClips(float value) {
    dynet_swigJNI.Trainer_clips_set(swigCPtr, this, value);
  }

  public float getClips() {
    return dynet_swigJNI.Trainer_clips_get(swigCPtr, this);
  }

  public void setUpdates(float value) {
    dynet_swigJNI.Trainer_updates_set(swigCPtr, this, value);
  }

  public float getUpdates() {
    return dynet_swigJNI.Trainer_updates_get(swigCPtr, this);
  }

  public void setClips_since_status(float value) {
    dynet_swigJNI.Trainer_clips_since_status_set(swigCPtr, this, value);
  }

  public float getClips_since_status() {
    return dynet_swigJNI.Trainer_clips_since_status_get(swigCPtr, this);
  }

  public void setUpdates_since_status(float value) {
    dynet_swigJNI.Trainer_updates_since_status_set(swigCPtr, this, value);
  }

  public float getUpdates_since_status() {
    return dynet_swigJNI.Trainer_updates_since_status_get(swigCPtr, this);
  }

  public void setSparse_updates_enabled(boolean value) {
    dynet_swigJNI.Trainer_sparse_updates_enabled_set(swigCPtr, this, value);
  }

  public boolean getSparse_updates_enabled() {
    return dynet_swigJNI.Trainer_sparse_updates_enabled_get(swigCPtr, this);
  }

  public void setAux_allocated(long value) {
    dynet_swigJNI.Trainer_aux_allocated_set(swigCPtr, this, value);
  }

  public long getAux_allocated() {
    return dynet_swigJNI.Trainer_aux_allocated_get(swigCPtr, this);
  }

  public void setAux_allocated_lookup(long value) {
    dynet_swigJNI.Trainer_aux_allocated_lookup_set(swigCPtr, this, value);
  }

  public long getAux_allocated_lookup() {
    return dynet_swigJNI.Trainer_aux_allocated_lookup_get(swigCPtr, this);
  }

  public void status() {
    dynet_swigJNI.Trainer_status(swigCPtr, this);
  }

  public void setModel(ParameterCollection value) {
    dynet_swigJNI.Trainer_model_set(swigCPtr, this, ParameterCollection.getCPtr(value), value);
  }

  public ParameterCollection getModel() {
    long cPtr = dynet_swigJNI.Trainer_model_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ParameterCollection(cPtr, false);
  }

}
