/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class TreeLSTMBuilder extends RNNBuilder {
  private transient long swigCPtr;

  protected TreeLSTMBuilder(long cPtr, boolean cMemoryOwn) {
    super(dynet_swigJNI.TreeLSTMBuilder_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TreeLSTMBuilder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_TreeLSTMBuilder(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void set_num_elements(int num) {
    dynet_swigJNI.TreeLSTMBuilder_set_num_elements(swigCPtr, this, num);
  }

  public Expression add_input(int id, IntVector children, Expression x) {
    return new Expression(dynet_swigJNI.TreeLSTMBuilder_add_input(swigCPtr, this, id, IntVector.getCPtr(children), children, Expression.getCPtr(x), x), true);
  }

  public ExpressionVector final_h() {
    return new ExpressionVector(dynet_swigJNI.TreeLSTMBuilder_final_h(swigCPtr, this), true);
  }

  public ExpressionVector final_s() {
    return new ExpressionVector(dynet_swigJNI.TreeLSTMBuilder_final_s(swigCPtr, this), true);
  }

  public ExpressionVector get_h(int i) {
    return new ExpressionVector(dynet_swigJNI.TreeLSTMBuilder_get_h(swigCPtr, this, i), true);
  }

  public ExpressionVector get_s(int i) {
    return new ExpressionVector(dynet_swigJNI.TreeLSTMBuilder_get_s(swigCPtr, this, i), true);
  }

  public long num_h0_components() {
    return dynet_swigJNI.TreeLSTMBuilder_num_h0_components(swigCPtr, this);
  }

  public void copy(RNNBuilder params) {
    dynet_swigJNI.TreeLSTMBuilder_copy(swigCPtr, this, RNNBuilder.getCPtr(params), params);
  }

}
