/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class AdadeltaTrainer extends Trainer {
  private transient long swigCPtr;

  protected AdadeltaTrainer(long cPtr, boolean cMemoryOwn) {
    super(dynet_swigJNI.AdadeltaTrainer_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AdadeltaTrainer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_AdadeltaTrainer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AdadeltaTrainer(ParameterCollection m, float eps, float rho) {
    this(dynet_swigJNI.new_AdadeltaTrainer__SWIG_0(ParameterCollection.getCPtr(m), m, eps, rho), true);
  }

  public AdadeltaTrainer(ParameterCollection m, float eps) {
    this(dynet_swigJNI.new_AdadeltaTrainer__SWIG_1(ParameterCollection.getCPtr(m), m, eps), true);
  }

  public AdadeltaTrainer(ParameterCollection m) {
    this(dynet_swigJNI.new_AdadeltaTrainer__SWIG_2(ParameterCollection.getCPtr(m), m), true);
  }

  public void restart() {
    dynet_swigJNI.AdadeltaTrainer_restart(swigCPtr, this);
  }

}
