/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public final class DeviceMempool {
  public final static DeviceMempool FXS = new DeviceMempool("FXS", dynet_swigJNI.DeviceMempool_FXS_get());
  public final static DeviceMempool DEDFS = new DeviceMempool("DEDFS", dynet_swigJNI.DeviceMempool_DEDFS_get());
  public final static DeviceMempool PS = new DeviceMempool("PS", dynet_swigJNI.DeviceMempool_PS_get());
  public final static DeviceMempool SCS = new DeviceMempool("SCS", dynet_swigJNI.DeviceMempool_SCS_get());
  public final static DeviceMempool NONE = new DeviceMempool("NONE", dynet_swigJNI.DeviceMempool_NONE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static DeviceMempool swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + DeviceMempool.class + " with value " + swigValue);
  }

  private DeviceMempool(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private DeviceMempool(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private DeviceMempool(String swigName, DeviceMempool swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static DeviceMempool[] swigValues = { FXS, DEDFS, PS, SCS, NONE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

