/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class DeviceMempoolSizes {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DeviceMempoolSizes(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DeviceMempoolSizes obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_DeviceMempoolSizes(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUsed(SWIGTYPE_p_size_t value) {
    dynet_swigJNI.DeviceMempoolSizes_used_set(swigCPtr, this, SWIGTYPE_p_size_t.getCPtr(value));
  }

  public SWIGTYPE_p_size_t getUsed() {
    long cPtr = dynet_swigJNI.DeviceMempoolSizes_used_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_size_t(cPtr, false);
  }

  public DeviceMempoolSizes() {
    this(dynet_swigJNI.new_DeviceMempoolSizes__SWIG_0(), true);
  }

  public DeviceMempoolSizes(long total_s) {
    this(dynet_swigJNI.new_DeviceMempoolSizes__SWIG_1(total_s), true);
  }

  public DeviceMempoolSizes(long fxs_s, long dEdfs_s, long ps_s, long sc_s) {
    this(dynet_swigJNI.new_DeviceMempoolSizes__SWIG_2(fxs_s, dEdfs_s, ps_s, sc_s), true);
  }

  public DeviceMempoolSizes(String descriptor) {
    this(dynet_swigJNI.new_DeviceMempoolSizes__SWIG_3(descriptor), true);
  }

}
