/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class FastLSTMBuilder extends RNNBuilder {
  private transient long swigCPtr;

  protected FastLSTMBuilder(long cPtr, boolean cMemoryOwn) {
    super(dynet_swigJNI.FastLSTMBuilder_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FastLSTMBuilder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_FastLSTMBuilder(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public FastLSTMBuilder() {
    this(dynet_swigJNI.new_FastLSTMBuilder__SWIG_0(), true);
  }

  public FastLSTMBuilder(long layers, long input_dim, long hidden_dim, ParameterCollection model) {
    this(dynet_swigJNI.new_FastLSTMBuilder__SWIG_1(layers, input_dim, hidden_dim, ParameterCollection.getCPtr(model), model), true);
  }

  public Expression back() {
    return new Expression(dynet_swigJNI.FastLSTMBuilder_back(swigCPtr, this), true);
  }

  public ExpressionVector final_h() {
    return new ExpressionVector(dynet_swigJNI.FastLSTMBuilder_final_h(swigCPtr, this), true);
  }

  public ExpressionVector final_s() {
    return new ExpressionVector(dynet_swigJNI.FastLSTMBuilder_final_s(swigCPtr, this), true);
  }

  public long num_h0_components() {
    return dynet_swigJNI.FastLSTMBuilder_num_h0_components(swigCPtr, this);
  }

  public ExpressionVector get_h(int i) {
    return new ExpressionVector(dynet_swigJNI.FastLSTMBuilder_get_h(swigCPtr, this, i), true);
  }

  public ExpressionVector get_s(int i) {
    return new ExpressionVector(dynet_swigJNI.FastLSTMBuilder_get_s(swigCPtr, this, i), true);
  }

  public void copy(RNNBuilder params) {
    dynet_swigJNI.FastLSTMBuilder_copy(swigCPtr, this, RNNBuilder.getCPtr(params), params);
  }

  public ParameterCollection get_parameter_collection() {
    return new ParameterCollection(dynet_swigJNI.FastLSTMBuilder_get_parameter_collection(swigCPtr, this), false);
  }

  public void setLocal_model(ParameterCollection value) {
    dynet_swigJNI.FastLSTMBuilder_local_model_set(swigCPtr, this, ParameterCollection.getCPtr(value), value);
  }

  public ParameterCollection getLocal_model() {
    long cPtr = dynet_swigJNI.FastLSTMBuilder_local_model_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ParameterCollection(cPtr, false);
  }

  public void setParams(ParameterVectorVector value) {
    dynet_swigJNI.FastLSTMBuilder_params_set(swigCPtr, this, ParameterVectorVector.getCPtr(value), value);
  }

  public ParameterVectorVector getParams() {
    long cPtr = dynet_swigJNI.FastLSTMBuilder_params_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ParameterVectorVector(cPtr, false);
  }

  public void setParam_vars(ExpressionVectorVector value) {
    dynet_swigJNI.FastLSTMBuilder_param_vars_set(swigCPtr, this, ExpressionVectorVector.getCPtr(value), value);
  }

  public ExpressionVectorVector getParam_vars() {
    long cPtr = dynet_swigJNI.FastLSTMBuilder_param_vars_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ExpressionVectorVector(cPtr, false);
  }

  public void setH(ExpressionVectorVector value) {
    dynet_swigJNI.FastLSTMBuilder_h_set(swigCPtr, this, ExpressionVectorVector.getCPtr(value), value);
  }

  public ExpressionVectorVector getH() {
    long cPtr = dynet_swigJNI.FastLSTMBuilder_h_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ExpressionVectorVector(cPtr, false);
  }

  public void setC(ExpressionVectorVector value) {
    dynet_swigJNI.FastLSTMBuilder_c_set(swigCPtr, this, ExpressionVectorVector.getCPtr(value), value);
  }

  public ExpressionVectorVector getC() {
    long cPtr = dynet_swigJNI.FastLSTMBuilder_c_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ExpressionVectorVector(cPtr, false);
  }

  public void setHas_initial_state(boolean value) {
    dynet_swigJNI.FastLSTMBuilder_has_initial_state_set(swigCPtr, this, value);
  }

  public boolean getHas_initial_state() {
    return dynet_swigJNI.FastLSTMBuilder_has_initial_state_get(swigCPtr, this);
  }

  public void setH0(ExpressionVector value) {
    dynet_swigJNI.FastLSTMBuilder_h0_set(swigCPtr, this, ExpressionVector.getCPtr(value), value);
  }

  public ExpressionVector getH0() {
    long cPtr = dynet_swigJNI.FastLSTMBuilder_h0_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ExpressionVector(cPtr, false);
  }

  public void setC0(ExpressionVector value) {
    dynet_swigJNI.FastLSTMBuilder_c0_set(swigCPtr, this, ExpressionVector.getCPtr(value), value);
  }

  public ExpressionVector getC0() {
    long cPtr = dynet_swigJNI.FastLSTMBuilder_c0_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ExpressionVector(cPtr, false);
  }

  public void setLayers(long value) {
    dynet_swigJNI.FastLSTMBuilder_layers_set(swigCPtr, this, value);
  }

  public long getLayers() {
    return dynet_swigJNI.FastLSTMBuilder_layers_get(swigCPtr, this);
  }

}
