/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class FloatVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FloatVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FloatVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_FloatVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FloatVector(java.util.Collection<Float> values) {
     this(values.size());
     int i = 0;
     for (java.util.Iterator<Float> it = values.iterator(); it.hasNext(); i++) {
         Float value = it.next();
         this.set(i, value);
     }
  }

  public FloatVector() {
    this(dynet_swigJNI.new_FloatVector__SWIG_0(), true);
  }

  public FloatVector(long n) {
    this(dynet_swigJNI.new_FloatVector__SWIG_1(n), true);
  }

  public long size() {
    return dynet_swigJNI.FloatVector_size(swigCPtr, this);
  }

  public long capacity() {
    return dynet_swigJNI.FloatVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    dynet_swigJNI.FloatVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return dynet_swigJNI.FloatVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    dynet_swigJNI.FloatVector_clear(swigCPtr, this);
  }

  public void add(float x) {
    dynet_swigJNI.FloatVector_add(swigCPtr, this, x);
  }

  public float get(int i) {
    return dynet_swigJNI.FloatVector_get(swigCPtr, this, i);
  }

  public void set(int i, float val) {
    dynet_swigJNI.FloatVector_set(swigCPtr, this, i, val);
  }

}
