/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class IntVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IntVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_IntVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IntVector(java.util.Collection<Integer> values) {
     this(values.size());
     int i = 0;
     for (java.util.Iterator<Integer> it = values.iterator(); it.hasNext(); i++) {
         Integer value = it.next();
         this.set(i, value);
     }
  }

  public IntVector() {
    this(dynet_swigJNI.new_IntVector__SWIG_0(), true);
  }

  public IntVector(long n) {
    this(dynet_swigJNI.new_IntVector__SWIG_1(n), true);
  }

  public long size() {
    return dynet_swigJNI.IntVector_size(swigCPtr, this);
  }

  public long capacity() {
    return dynet_swigJNI.IntVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    dynet_swigJNI.IntVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return dynet_swigJNI.IntVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    dynet_swigJNI.IntVector_clear(swigCPtr, this);
  }

  public void add(int x) {
    dynet_swigJNI.IntVector_add(swigCPtr, this, x);
  }

  public int get(int i) {
    return dynet_swigJNI.IntVector_get(swigCPtr, this, i);
  }

  public void set(int i, int val) {
    dynet_swigJNI.IntVector_set(swigCPtr, this, i, val);
  }

}
