/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class LookupParameter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LookupParameter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LookupParameter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_LookupParameter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LookupParameter() {
    this(dynet_swigJNI.new_LookupParameter(), true);
  }

  public void initialize(long index, FloatVector val) {
    dynet_swigJNI.LookupParameter_initialize(swigCPtr, this, index, FloatVector.getCPtr(val), val);
  }

  public void zero() {
    dynet_swigJNI.LookupParameter_zero(swigCPtr, this);
  }

  public Dim dim() {
    return new Dim(dynet_swigJNI.LookupParameter_dim(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorT_dynet__Tensor_t values() {
    long cPtr = dynet_swigJNI.LookupParameter_values(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_dynet__Tensor_t(cPtr, false);
  }

  public void set_updated(boolean b) {
    dynet_swigJNI.LookupParameter_set_updated(swigCPtr, this, b);
  }

  public boolean is_updated() {
    return dynet_swigJNI.LookupParameter_is_updated(swigCPtr, this);
  }

}
