/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.dynet.internal;

public class UnsignedVectorVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UnsignedVectorVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UnsignedVectorVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        dynet_swigJNI.delete_UnsignedVectorVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UnsignedVectorVector(java.util.Collection<UnsignedVector> values) {
     this(values.size());
     int i = 0;
     for (java.util.Iterator<UnsignedVector> it = values.iterator(); it.hasNext(); i++) {
         UnsignedVector value = it.next();
         this.set(i, value);
     }
  }

  public UnsignedVectorVector() {
    this(dynet_swigJNI.new_UnsignedVectorVector__SWIG_0(), true);
  }

  public UnsignedVectorVector(long n) {
    this(dynet_swigJNI.new_UnsignedVectorVector__SWIG_1(n), true);
  }

  public long size() {
    return dynet_swigJNI.UnsignedVectorVector_size(swigCPtr, this);
  }

  public long capacity() {
    return dynet_swigJNI.UnsignedVectorVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    dynet_swigJNI.UnsignedVectorVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return dynet_swigJNI.UnsignedVectorVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    dynet_swigJNI.UnsignedVectorVector_clear(swigCPtr, this);
  }

  public void add(UnsignedVector x) {
    dynet_swigJNI.UnsignedVectorVector_add(swigCPtr, this, UnsignedVector.getCPtr(x), x);
  }

  public UnsignedVector get(int i) {
    return new UnsignedVector(dynet_swigJNI.UnsignedVectorVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, UnsignedVector val) {
    dynet_swigJNI.UnsignedVectorVector_set(swigCPtr, this, i, UnsignedVector.getCPtr(val), val);
  }

}
